### ISSUE TITLE
Develop Openscapes Pathway and prepare for cohort presentation

### ISSUE THREAD

**Issue by Curt-Whitmire-NOAA** [NWFSC-Eco-Stock-assessments/ESA-collaboration#9]
Hi Team,

We need to develop our pathway and prepare to present it during our last cohort call this Friday, the 29th. If you recall, we began to develop our [pathway](https://docs.google.com/spreadsheets/d/1Ih4Lz_-YmVGHz18Q_FrzGR9B6v1VwghUGxl9BDPq6aQ/edit#gid=0) about a month ago, but it would be nice to try to fill in some more details to help develop a presentation.

Please take a look and fill in what you can. We are not beholden to this template, so feel free to adjust as needed.

**Comment by kellijohnson-NOAA** [comment]
Sorry for the pessimistic view of Pathways, but I feel this exercise is not very helpful for our team. Especially given that we didn't really work on a project together. I think instead, we could highlight information that we talked about regarding maybe what we would like to see for a Pathway for the whole center, like #7.

**Comment by Curt-Whitmire-NOAA** [comment]
I appreciate that @kellijohnson-NOAA. I too was struggling with how to develop a pathway, and present it, giving our team composition. I agree that we could instead present some suggestions about better Center-wide integration of open science principles that may increase collaboration and efficiencies. The parent GH org is a good place to start, along with some others I've been thinking about. I did start populating some things on the [Pathway](https://docs.google.com/spreadsheets/d/1Ih4Lz_-YmVGHz18Q_FrzGR9B6v1VwghUGxl9BDPq6aQ/edit#gid=0) sheet that may or may not be useful.

Would you be willing to present if we all chip in on the details?

**Comment by ntolimieri** [comment]
My apologies, but I've been buried in other stuff...I'll try to read through stuff and catch up but I'm probably just an observer until Friday AM at the earliest.

**Comment by Curt-Whitmire-NOAA** [comment]
No worries, @tolimieri. We've all been busy with our day jobs. Anything you can contribute, even during the Q&A Friday is much appreciated.

**Comment by Curt-Whitmire-NOAA** [comment]
I'll try to put a slide or two together, summarizing some main points of our discussions over the past couple of months.

**Comment by cj-harvey** [comment]
@Curt-Whitmire-NOAA I will add some opinions I shared at our last Seaside chat to the "Culture" portion of the Pathway. Maybe that will be helpful, maybe not!

**Comment by Curt-Whitmire-NOAA** [comment]
Thanks @cj-harvey. My appreciated!

**Comment by Curt-Whitmire-NOAA** [comment]
@cj-harvey , I hope you didn't mind me quoting you directly today during or Pathway presentation. I thought you summed up the challenges nicely, and it was a nice introduction to the idea of cultural change I was trying to make.

**Comment by kellijohnson-NOAA** [comment]
Sorry I missed the call, I have been sick all week.

**Comment by Curt-Whitmire-NOAA** [comment]
Bummer Kelli, I hope you feel better soon. It was a good discussion today that kind of wrapped up the main themes of this cohort, with some good suggestions about how we improve open science principles across our orgs.
